SELECT
    CURRENT_USER() AS DEPLOY_USER,
    CURRENT_ROLE() AS DEPLOY_ROLE,
    CURRENT_DATABASE() AS DEPLOY_DATABASE,
    CURRENT_SCHEMA() AS DEPLOY_SCHEMA,
    CURRENT_WAREHOUSE() AS DEPLOY_WAREHOUSE,
    CURRENT_TIMESTAMP() AS DEPLOYED_AT;